/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id:
    "us-east-2:2592109e-6982-401a-a50a-98ae022a2dc2",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_SsMdZ0Dso",
  aws_user_pools_web_client_id: "1amqacbpj7vontrem6glc8ou14",
  oauth: {},
};
export default awsmobile;
